### ISSUE TITLE
can OmniGen inference with torch.float16?

### ISSUE THREAD

**Issue by hrz2000** [VectorSpaceLab/OmniGen#166]
<img width="679" alt="image" src="https://github.com/user-attachments/assets/d3054616-5474-4bc2-b2e8-be15f7b7e5e0" />
I noticed that the default precision is bfloat16, which takes 29 seconds. When I replaced it with float16, it only took 9 seconds, but the generated image was completely black.

**Comment by able2608** [comment]
bfloat16 covers the numeric range of float32 with half the memory requirements (by reducing precision, which is not that important for generation tasks like this), while float16 has a much smaller numeric range. Directly using float16 inference on a float32-native model may cause overflow, since the model was trained to output numbers out of the range of what float16 can hold.
To address the blank output issue (which is caused by output overflow), the easiest way will be to simply clamp the value the model output to what float16 can hold, at the potential cost of performance degradation. To retain the performance, quantization might need to be performed. Thus for now it would be best just keep bf16 inference.
BTW, there is an active fork of this repo that implements quantization with proper libraries. If that is what you are looking for, check it out here https://github.com/Rypo/OmniGen/tree/bnb_quantization. I am not able to test whether this version has a better performance due to my lack of supporting hardware to run the unquantized version, but perhaps you can test it yourself and see which fits you best.

**Comment by hrz2000** [comment]
Thanks for your kindly reply!
