### ISSUE TITLE
about data mix radio.

### ISSUE THREAD

**Issue by budui** [VectorSpaceLab/OmniGen#42]
Hello, first of all, thank you for sharing your impressive work and open-sourcing the weights!

The paper describes in detail the source and composition of a lot of data. Unfortunately, it does not describe much information about the data mix ratio. Could you please disclose the mixing probability of data for different tasks? Does the mixing ratio of data need to be adjusted at different stages (resolution) of training?

**Comment by staoxiao** [comment]
Thanks for your attention to our work! 
The dataset will be released in the future. As for the training data mixing ratio, we do not have a fixed strategy because some data were added later. The general approach is that, in the early stages of training, no specific ratio is set, aiming for each dataset to be seen. In the later stages of training, we sample different tasks with different ratios: t2i: 0.5, subject-driven: 0.2, ControlNet: 0.1,  edit: 0.1, others: 0.1
